### ISSUE TITLE
is_url fails on '-'

### ISSUE THREAD

**Issue by eyal666** [theteladras/py.validator#4]
`is_url` function failing when passing an URL with a hyphen, for example: `abc-d.com` will fail

**Comment by theteladras** [comment]
Thank you very much for reporting the bug! I'll take care of it soon!

**Comment by theteladras** [comment]
I have just deployed the version **0.8.1** with the fix. If that does sort it out, just let me know so we can close the issue.
Thanks again for reporting, if you do spot any additional bugs please do report!

**Comment by theteladras** [comment]
Considering this as solved.
