### ISSUE TITLE
`is_url` function failing when top level domain is longer than 6 chars.  

### ISSUE THREAD

**Issue by mikeynagler** [theteladras/py.validator#5]
Restricting the top level domain to a max of length of 6 chars fails when top level domain is longer. 
e.g.:
`'www.testing.testing' //False`

due to this within `is_url`:
`top_level_domain_pattern = r"\.[a-z]{2,6}"`

Can we get the option to pass it as a param? or just make it somewhat longer?

**Comment by theteladras** [comment]
Hey @mikeynagler, thanks for reporting this issue! Yeah that is true, the TLD should be limited to 63 characters. I'll do a fix shortly.

_A reference of the TLD length definition can be found [here](https://tools.ietf.org/id/draft-liman-tld-names-00.html#:~:text=A%20TLD%20label%20MUST%20be%20at%20least%20two%20characters%20long%20and%20MAY%20be%20as%20long%20as%2063%20characters)_

**Comment by theteladras** [comment]
@mikeynagler This has been changed in the latest commit. If you can confirm that all is as expected, that would be awesome and we can close the issue.

**Comment by mikeynagler** [comment]
fixed. thanks!
